## Promise对象的错误的冒泡性质
- Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获。
- catch方法返回的仍然是一个Promise对象，因此后面还可以接着调用then方法